# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08bdfb0507172fc5f3a6f2f754a1eab77f82c96bc83a8b6ebc612ca8a1c9f52f56f56c6116222cfdb717d21e463d81cda866c547d0e3a4f4d3081b0386d3cd2c

test:
  secret_key_base: 5e5a6b6eb1ed301802d1210abd382f58fb29041b3cf09e2da0cf4d9085f8d2b6b7d486dd08c28dde0828f44acc0ae34a7efd2f06ad1db410f1477ef44bbc210b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
